global using FluentAssertions;
global using MercurySchool.Api.Models;
global using MercurySchool.Api.Models.Settings;
global using MercurySchool.Api.Repositories;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging.Abstractions;
global using System;
global using System.Threading.Tasks;
global using Xunit;
