name: mercury-school-deployment

on: 
  push:
    branches:
      - main

jobs:
  build-bicep:

    name: Build Bicep File

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.201
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with: 
          azcliversion: 2.20.0
          inlineScript: |
            az bicep build --files arm-templates/main.bicep