name: Mercury School Build and Deploy

# Controls when the action will run. 
on:
  [push, workflow_dispatch]

jobs:

  deploy:
    name: Mercury School Deployment
    runs-on: ubuntu-20.04
    environment: Production
    env:  
      ResourceGroupName: mercury-school

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create \
            --name ${{ env.ResourceGroupName }} \
            --location northcentralus \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ARM template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name mercury-school-deployment-${{github.run_number}} \
            -g ${{ env.ResourceGroupName }} \
            -f ./arm-templates/main.bicep \
            --parameters runid=${{github.run_number}} adAdminlogin="${{ secrets.AZURE_AD_ADMINISTRATOR_LOGIN }}" adAdminTenantId=${{ secrets.AZURE_AD_ADMINISTRATOR_TENANT_ID }} adAdminSid=${{ secrets.AZURE_AD_ADMINISTRATOR_SID }} administratorLogin=${{ secrets.SQL_ADMINISTRATOR_LOGIN }} administratorLoginPassword=${{ secrets.SQL_ADMINISTRATOR_LOGIN_PASSWORD }} 