name: mercury-school-deployment

on: 
  push:
    branches:
      - main

jobs:
  build-bicep:

    name: Build Bicep File

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!